/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Clases.Funciones;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author andre
 */
public class IDPUENTES extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public IDPUENTES() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CargarArchivo = new javax.swing.JButton();
        BotonSalirMenu = new javax.swing.JButton();
        MostrarPuentes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        CargarArchivo.setText("Cargar Archivo");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(CargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        BotonSalirMenu.setBackground(new java.awt.Color(255, 51, 51));
        BotonSalirMenu.setText("X");
        BotonSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirMenuActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalirMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 12, 40, -1));

        MostrarPuentes.setEditable(false);
        MostrarPuentes.setBackground(new java.awt.Color(255, 255, 255));
        MostrarPuentes.setAutoscrolls(false);
        MostrarPuentes.setFocusable(false);
        MostrarPuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarPuentesActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarPuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 440, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirMenuActionPerformed
        this.dispose();
        VentanaMenu vm1 = new VentanaMenu();
        vm1.setVisible(true);
        vm1.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BotonSalirMenuActionPerformed

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        try {
            String g = Funciones.leerRelaciones();
            MostrarPuentes.setText(g);
        } catch (IOException ex) {
            Logger.getLogger(IDPUENTES.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_CargarArchivoActionPerformed

    private void MostrarPuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPuentesActionPerformed

    }//GEN-LAST:event_MostrarPuentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDPUENTES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDPUENTES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDPUENTES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDPUENTES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDPUENTES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalirMenu;
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JTextField MostrarPuentes;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
