/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author andre
 */
public class Ventana1_1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1_1
     */
    public Ventana1_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CargArchivo = new javax.swing.JToggleButton();
        ActArchivos = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        BotonSalirMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CargArchivo.setText("Carga de archivo");
        CargArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(CargArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 72, 143, -1));

        ActArchivos.setText("Actualizacion de archivos");
        ActArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActArchivosActionPerformed(evt);
            }
        });
        getContentPane().add(ActArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 202, -1, -1));

        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSalirMenu.setBackground(new java.awt.Color(255, 51, 51));
        BotonSalirMenu.setText("X");
        BotonSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirMenuActionPerformed(evt);
            }
        });
        jPanel1.add(BotonSalirMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 40, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 6, 390, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActArchivosActionPerformed
        this.dispose();
        Ventana1_2 vm1 = new Ventana1_2();
        vm1.setVisible(true);
        vm1.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_ActArchivosActionPerformed

    private void CargArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargArchivoActionPerformed
        this.dispose();
        Ventana1 v2 = new Ventana1();
        v2.setVisible(true);
        v2.setLocationRelativeTo(null);

    }//GEN-LAST:event_CargArchivoActionPerformed

    private void BotonSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirMenuActionPerformed
        this.dispose();
        VentanaMenu vm1 = new VentanaMenu();
        vm1.setVisible(true);
        vm1.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BotonSalirMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ActArchivos;
    private javax.swing.JButton BotonSalirMenu;
    private javax.swing.JToggleButton CargArchivo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
