/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CargarArchivo = new javax.swing.JButton();
        MostrarDireccion = new javax.swing.JTextField();
        BotonSalirMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        CargarArchivo.setText("Cargar Archivo");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(CargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        MostrarDireccion.setEditable(false);
        MostrarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 280, -1));

        BotonSalirMenu.setBackground(new java.awt.Color(255, 51, 51));
        BotonSalirMenu.setText("X");
        BotonSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirMenuActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalirMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 12, 40, -1));

        jLabel1.setText("Dale click al boton \"Cargar Archivo\" y siga las instrucciones");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        try {
            JFileChooser elegir = new JFileChooser();
            elegir.showOpenDialog(null);
            File f = elegir.getSelectedFile();
            String nombrearchivo = f.getAbsolutePath();
            MostrarDireccion.setText(nombrearchivo);
            int mensaje = JOptionPane.showInternalConfirmDialog(null, "Quieres guardar este archivo?");
            if (mensaje == JOptionPane.YES_OPTION) {
                if (MostrarDireccion.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "No tienes ningun archivo seleccionado");

                } else {
                    try {
                        // Abre el archivo de entrada
                        BufferedReader reader = new BufferedReader(new FileReader(nombrearchivo));

                        // Abre el archivo de salida
                        FileWriter writer = new FileWriter("test\\Data\\usuarios.txt");

                        // Lee cada línea del archivo de entrada y la escribe en el archivo de salida
                        String linea;
                        while ((linea = reader.readLine()) != null) {
                            writer.write(linea + "\n");
                        }

                        // Cierra los archivos
                        reader.close();
                        writer.close();

                        JOptionPane.showMessageDialog(null, "Se ha guardado el archivo");

                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(null, "No se ha podido guardar el archivo intentelo de nuevo");
                        e.printStackTrace();
                    }
                    VentanaMenu vm1 = new VentanaMenu();
                    vm1.setVisible(true);
                    vm1.setLocationRelativeTo(null);
                    this.dispose();
                }
            }
            if (mensaje == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "No se ha guardado ningun archivo");
                VentanaMenu vm1 = new VentanaMenu();
                vm1.setVisible(true);
                vm1.setLocationRelativeTo(null);
                this.dispose();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cancelado");
        }

    }//GEN-LAST:event_CargarArchivoActionPerformed

    private void MostrarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarDireccionActionPerformed

    }//GEN-LAST:event_MostrarDireccionActionPerformed

    private void BotonSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirMenuActionPerformed
        this.dispose();
        Ventana1_1 vm1 = new Ventana1_1();
        vm1.setVisible(true);
        vm1.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BotonSalirMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalirMenu;
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JTextField MostrarDireccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
