/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import Clases.Funciones;
        
/**
 *
 * @author andre
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public VentanaMenu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        FondoMenu = new javax.swing.JPanel();
        TituloMenu = new javax.swing.JLabel();
        BotonSalirMenu = new javax.swing.JButton();
        CargarArchivos = new javax.swing.JButton();
        ReporteDisponibilidadAlmacen = new javax.swing.JButton();
        RealizarPedido = new javax.swing.JButton();
        SolicitarProductosOtroAlmacen = new javax.swing.JButton();
        AgregarAlmacen = new javax.swing.JButton();
        AgregarCamino = new javax.swing.JButton();
        StockAlmacen = new javax.swing.JButton();
        MostrarGrafo = new javax.swing.JButton();
        SubTitulo = new javax.swing.JLabel();
        CerrarPrograma = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoMenu.setMinimumSize(new java.awt.Dimension(500, 400));
        FondoMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloMenu.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        TituloMenu.setText("Bienvenido a OrganizedChaos");
        FondoMenu.add(TituloMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 40, -1, -1));

        BotonSalirMenu.setBackground(new java.awt.Color(255, 51, 51));
        BotonSalirMenu.setText("X");
        BotonSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirMenuActionPerformed(evt);
            }
        });
        FondoMenu.add(BotonSalirMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 12, -1, -1));

        CargarArchivos.setText("1. Cargar y actualizacion de archivos");
        CargarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivosActionPerformed(evt);
            }
        });
        FondoMenu.add(CargarArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 118, -1, -1));

        ReporteDisponibilidadAlmacen.setText("2. Reportes de disponibilidad por almacen");
        ReporteDisponibilidadAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteDisponibilidadAlmacenActionPerformed(evt);
            }
        });
        FondoMenu.add(ReporteDisponibilidadAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        RealizarPedido.setText("3. Realizar pedido");
        FondoMenu.add(RealizarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        SolicitarProductosOtroAlmacen.setText("4. Solicitar productos a otro almacén");
        FondoMenu.add(SolicitarProductosOtroAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        AgregarAlmacen.setText("5. Agregar un nuevo almacén");
        FondoMenu.add(AgregarAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        AgregarCamino.setText("6. Agregar un nuevo camino");
        FondoMenu.add(AgregarCamino, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        StockAlmacen.setText("7. Gestión de stock de un almacén");
        FondoMenu.add(StockAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        MostrarGrafo.setText("8. Mostrar grafo");
        FondoMenu.add(MostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        SubTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SubTitulo.setText("Dale Click a la opcion que prefiera:");
        FondoMenu.add(SubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 84, -1, -1));

        CerrarPrograma.setBackground(new java.awt.Color(255, 204, 204));
        CerrarPrograma.setText("CERRAR PROGRAMA");
        CerrarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarProgramaActionPerformed(evt);
            }
        });
        FondoMenu.add(CerrarPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 342, -1, -1));

        getContentPane().add(FondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirMenuActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotonSalirMenuActionPerformed

    private void CargarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivosActionPerformed
        this.dispose();
        Ventana1_1 v2 = new Ventana1_1();
        v2.setVisible(true);
        v2.setLocationRelativeTo(null);

    }//GEN-LAST:event_CargarArchivosActionPerformed

    private void CerrarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarProgramaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CerrarProgramaActionPerformed

    private void ReporteDisponibilidadAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteDisponibilidadAlmacenActionPerformed
        
    }//GEN-LAST:event_ReporteDisponibilidadAlmacenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                VentanaMenu v1 = new VentanaMenu();
                v1.setVisible(true);
                v1.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarAlmacen;
    private javax.swing.JButton AgregarCamino;
    private javax.swing.JButton BotonSalirMenu;
    private javax.swing.JButton CargarArchivos;
    private javax.swing.JButton CerrarPrograma;
    private javax.swing.JPanel FondoMenu;
    private javax.swing.JButton MostrarGrafo;
    private javax.swing.JButton RealizarPedido;
    private javax.swing.JButton ReporteDisponibilidadAlmacen;
    private javax.swing.JButton SolicitarProductosOtroAlmacen;
    private javax.swing.JButton StockAlmacen;
    private javax.swing.JLabel SubTitulo;
    private javax.swing.JLabel TituloMenu;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables

    private Ventana1 Ventana1() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
